### PR TITLE
Use wsrv.nl service

### PR DESCRIPTION
**Pull request by suhan-paradkar**
Well.. Since Heroku stopped their free service.... Let's add wsrv.nl

### CODE REVIEW

**Review by jobobby04 — CHANGES_REQUESTED** [review]
Dont remove bandwidth Hero data saver, here are some suggestions on how to handle both

- Rename DataSaverImpl -> BandwidthHeroDataSaver
- Add WsrvDataSaver
- Replace the data saver switch preference with a ListPreference with 3 options disabled, bandwidth hero, and wsrv.nl, you will have to chnage the prefernce objects and keys, change the enabled preferences based on the version of data saver used

**Comment by suhan-paradkar** [comment]
> * Rename DataSaverImpl -> BandwidthHeroDataSaver
> * Add WsrvDataSaver

Well.. Instead of renaming DataSaverImpl and then Adding WsrvDataSaver..
I just modified DataSaverImpl to handle both DataSaver implementations...
 
> * Replace the data saver switch preference with a ListPreference with 3 options disabled, bandwidth hero, and wsrv.nl, you will have to chnage the prefernce objects and keys, change the enabled preferences based on the version of data saver used

Done

**Comment by suhan-paradkar** [comment]
@jobobby04 I guess It's done....

**Comment by jobobby04** [comment]
Close enough, I will do some code cleanup when I have time and then merge it

**Pull request merged**
