### PR TITLE
update screens

### PR DESCRIPTION
**Pull request by OncePunchedMan**

### CODE REVIEW

**Comment by OncePunchedMan** [comment]
needs a new Browse screen

**Comment by KraXen72** [comment]
original has the pink theme on second screenshot, yours doesen't.
image

also, why tf is your statusbar so big??? it's like 1cm tall mlao. orig. screenshots didn't have status bar

**Comment by joseph619** [comment]
Could replace the Latest thing with Feed now I suppose, since latest no longer exists 🙂

**Comment by joseph619** [comment]
I could show an example of feed tomorrow

**Comment by jobobby04** [comment]
Ended up making my own
[backup file I used to make it](https://github.com/jobobby04/TachiyomiSY/files/13930163/eu.kanade.tachiyomi.sy.debug_2024-01-13_18-54.tachibk.zip)

**Comment by KraXen72** [comment]
so much yuri in the screens, i bet @OncePunchedMan is pleased

**Pull request closed without merging**
