### PR TITLE
Show download state and progress on reader chapter list.

### LINKED ISSUE #1207: Downloads disappear
### Steps to reproduce

When you are just in the manhwa/manga it shows that the chapters are downloaded
But when you are reading one and then you pull up the chapter from the 3 horizontal bar line option even though its downloaded it doesn't show that it is but it still works as downloaded
Screenshot_20240611-152026
Screenshot_20240611-152038

### Expected behavior

It should show that downloaded tick in the 3 horizontal line option

### Actual behavior

It just doesn't show the tick but still works as downloaded

### Crash logs

_No response_

### TachiyomiSY version

App version: 1.10.5 (standard, 31f967235, 68, 2024-06-01T22:29:05Z) Preview build: 561 Android version: 13 (SDK 33; build CK6n-H6929CD-T-OP-240417V4796) Device brand: TECNO Device manufacturer: TECNO Device name: TECNO-CK6n (CK6n-OP) Device model: TECNO CK6n WebView: Android System WebView 125.0.6422.165

### Android version

Android 13

### Device

Tecno camon 20 (not pro,5g or premier)

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by NGB-Was-Taken**
Issues with my implementation:
- The download state and progress don't update until chapter is scrolled out of the screen and back or the chapter list dialogue is closed and re-opened.
- The button itself still does nothing.

Closes  #1207
(I am unsure whether #497 is mentioning this or something else and why Syer mentioned that it's intentional.)

### CODE REVIEW

**Comment by jobobby04** [comment]
Is this good to merge? I saw a lot of talk about it in the discord

**Comment by NGB-Was-Taken** [comment]
> Is this good to merge? I saw a lot of talk about it in the discord

Definitely not. It just "sort of" works. As I mentioned:
> The download state and progress don't update until chapter is scrolled out of the screen and back or the chapter list dialogue is closed and re-opened.

I have managed to make it update when the state changes (not committed) . No luck on the progress though. I think I'll be quite busy this week and won't be able to work on this. Should I mark this as draft or something?

**Comment by jobobby04** [comment]
Marking it as draft then 👍

**Comment by NGB-Was-Taken** [comment]
Should I add issue 497 to be closed by this? Context is lost without the images and I have no clue if it's mentioning this or something else.

**Comment by cuong-tran** [comment]
It still doesn't update the state after chapters are automatically deleted.

**Comment by NGB-Was-Taken** [comment]
> It still doesn't update the state after chapters are automatically deleted.

How do you even check for that? Automatic deletion of chapters (as far as I know) is done only after the `ReaderViewModel` is closed. https://github.com/jobobby04/TachiyomiSY/blob/dea38912fc788f9dddc4a22f19a995c0b25f7933/app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderViewModel.kt#L318-L324

**Review by jobobby04 — APPROVED** [review]

**Pull request merged**
