### PR TITLE
Fix label visibility for tablet ui

### PR DESCRIPTION
**Pull request by OncePunchedMan**
the long awaited fix finally released

### CODE REVIEW

**Comment by jobobby04** [comment]
I think this would work and be shorter
```kotlin
private fun setNavLabelVisibility() {
    if (preferences.bottomBarLabels().get()) {
        nav.labelVisibilityMode = NavigationBarView.LABEL_VISIBILITY_LABELED
    } else {
        nav.labelVisibilityMode = NavigationBarView.LABEL_VISIBILITY_SELECTED
    }
}
```

**Comment by OncePunchedMan** [comment]
the navigation rail has its own NavigationRailView tho

**Comment by jobobby04** [comment]
Only one of the navigation views are enabled at a time

**Comment by OncePunchedMan** [comment]
alright it did the magic! thx :*

**Comment by e-shl** [comment]
this https://github.com/jobobby04/TachiyomiSY/pull/324 also doesn't work in the sidebar

**Comment by OncePunchedMan** [comment]
how is this related

**Pull request merged**
