### PR TITLE
Cache manga from library

### PR DESCRIPTION
**Pull request by simakover**
After loading from backup or adding manga from sources without open manga, tags and chapters not load to cache, you need open each manga for load cache. So i made this implemetation.
On library screen you can choose multiple manga and use menu buttom "Cache manga" to load cache\tags\chapters\etc

### CODE REVIEW

**Comment by jobobby04** [comment]
I probably wont merge this, it seems like a simplified library update. I dont really see a need about adding another way to do it

**Comment by simakover** [comment]
@jobobby04 ok, then would update my mangas on dev build. usefull for me updating some manga, but not all the livrary. you can close this request

**Comment by simakover** [comment]
@jobobby04 may be you can check a #376 request?

**Comment by jobobby04** [comment]
Ya I have no problem with that one, I will be take a look at it when I have time

**Comment by simakover** [comment]
@jobobby04 found that some source exluded from libraryUpdate. Do you know why? 
`var LIBRARY_UPDATE_EXCLUDED_SOURCES = listOf(
    EH_SOURCE_ID,
    EXH_SOURCE_ID,
    TSUMINO_SOURCE_ID,
    PURURIN_SOURCE_ID
)`

**Comment by jobobby04** [comment]
E-H and EXH need to be severely rate limited so they have a separate updater. The others are there to speed up the library update since those sites do not update them once posted.

**Comment by simakover** [comment]
Tsumino dont update chapters? it looks like some of manga have new chapters there.
biggest reason for me - updating tags for sorting manga, but im cant update tsumino source because of that setting(

**Comment by jobobby04** [comment]
I have been meaning to remove tsumino from that list, it's there because the old internal tsumino didit have chapters

**Comment by simakover** [comment]
would be grateful

**Pull request closed without merging**
