### PR TITLE
hide update and history buttons option

### PR DESCRIPTION
**Pull request by simakover**
Add an option to hide update and history buttons in nivagation bar

### CODE REVIEW

**Comment by jobobby04** [comment]
Instead of hiding, make the option move it to More, then I will merge

**Comment by simakover** [comment]
> Instead of hiding, make the option move it to More, then I will merge

done

**Comment by jobobby04** [comment]
It will be merged before the next build 👍

**Comment by e-shl** [comment]
Oooh so notbad too https://github.com/jobobby04/TachiyomiSY/issues/276

**Comment by e-shl** [comment]
@jobobby04 
> Instead of hiding, make the option move it to More, then I will merge

maybe it's better to add them to the library?

**Comment by jobobby04** [comment]
Forgot to merge it, whatever ill just merge it after the check is done

**Comment by jobobby04** [comment]
> 
> 
> @jobobby04
> 
> > Instead of hiding, make the option move it to More, then I will merge
> 
> maybe it's better to add them to the library?
> 
> as optional settings an alternative More

No that wouldnt work out well, they would just hog the limited space

**Comment by e-shl** [comment]
@jobobby04 ?

**Comment by e-shl** [comment]
@jobobby04 maybe do made a double-click on the History to open the Updates, only when Updates is hidden? (how Downloads open when you click on Updates)

**Pull request merged**
