### PR TITLE
Add Theme Nice Booba Green

### PR DESCRIPTION
**Pull request by Riztard**
Add Theme Nice Booba Green

<table>
<tr>
	<td>
	<td>
	<td>
<tr>
	<td>
	<td>
	<td>
</table>

### CODE REVIEW

**Comment by jobobby04** [comment]
And this is why I have Cl builds

**Comment by OncePunchedMan** [comment]
pls no

**Comment by e-shl** [comment]
Is it like "Flat Lime" from J2K?

**Comment by e-shl** [comment]
Do need this topic/pull now?  Because SY now has a Green Apple

**Comment by jobobby04** [comment]
Nah

**Pull request closed without merging**
