### PR TITLE
[IDEA] change default to daily backup

### PR DESCRIPTION
**Pull request by OncePunchedMan**

### CODE REVIEW

**Comment by jobobby04** [comment]
You will likely have to add it to the setup tasks on first launch
Here for Main tachi:
https://github.com/jobobby04/TachiyomiSY/blob/master/app/src/main/java/eu/kanade/tachiyomi/Migrations.kt#L51

Here for SY
https://github.com/jobobby04/TachiyomiSY/blob/master/app/src/main/java/exh/EXHMigrations.kt#L76

**Comment by arkon** [comment]
You'd need to also prompt for storage permissions earlier in the app lifecycle.

**Comment by OncePunchedMan** [comment]
alright

**Comment by OncePunchedMan** [comment]
- [ ] add it to the setup tasks on first launch

- [ ] prompt for storage permissions earlier in the app lifecycle

**Pull request closed without merging**
