### PR TITLE
Reader PR (with vertical sidebar)

### PR DESCRIPTION
**Pull request by CrepeTF**
**vtuba bad**

- The vertical-left animation is applied on the right seekbar right after turning it on, but to show the left seekbar instad of right, you need to re-enter the reader.
- The vertical seekbar might "jump" when exiting reading menu mode (especially on large screens) due to layout constraints?

### CODE REVIEW

**Comment by CrepeTF** [comment]
A workaround could be to just keep the left-vertical seekbar setting to reader settings.

**Comment by CrepeTF** [comment]
rebiew pls ;(

**Comment by joseph619** [comment]
gotta update the new icons for vertical seekbar too i suppose?

**Comment by CrepeTF** [comment]
Yep, I'll sort these out tomorrow around 5pm

**Pull request merged**
