### PR TITLE
Add Theme AMOLEDblue analogue DarkBlue

### PR DESCRIPTION
**Pull request by e-shl**

### CODE REVIEW

**Comment by e-shl** [comment]
This is not a duplicate. The first PR https://github.com/jobobby04/TachiyomiSY/pull/274 broke due to changes in the program and I couldn't get github to merge the changes.

**Comment by e-shl** [comment]
@jobobby04 Ok?

**Comment by jobobby04** [comment]
I started a poll in the Tachiyomi discord server in the SY channel, if it wins this will be merged

**Comment by e-shl** [comment]
@jobobby04 

??(

**Pull request merged**
