### PR TITLE
Rus locale fix/additions

### PR DESCRIPTION
**Pull request by e-shl**
Clean version https://github.com/jobobby04/TachiyomiSY/pull/292 after https://github.com/tachiyomiorg/tachiyomi/pull/4996 .
This time merge it without waiting for the release.

### CODE REVIEW

**Comment by e-shl** [comment]
@jobobby04  the string do not have "Select target sources "Find in another source"

**Comment by jobobby04** [comment]
I'll export that to the xml for the next build

**Comment by e-shl** [comment]
@jobobby04  don't forget merge.

**Comment by jobobby04** [comment]
Ill do it now so I dont forget lol

**Pull request merged**
